# Generated by Django 5.1.7 on 2025-03-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('region', models.CharField(choices=[('Tashkent', 'Tashkent'), ('Samarqand', 'Samarqand'), ('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Farg‘ona', 'Farg‘ona'), ('Jizzax', 'Jizzax'), ('Xorazm', 'Xorazm'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxondaryo', 'Surxondaryo'), ('Sirdaryo', 'Sirdaryo'), ('Qoraqalpog‘iston', 'Qoraqalpog‘iston'), ('Toshkent shahri', 'Toshkent shahri')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
